# Generated by Django 3.1.1 on 2020-10-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mypick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_brand', models.CharField(blank=True, max_length=100, verbose_name='Top Brand')),
                ('top_product_name', models.CharField(blank=True, max_length=100, verbose_name='Top Product Name')),
                ('top_image', models.URLField(unique=True, verbose_name='Top Image URL')),
                ('pants_brand', models.CharField(blank=True, max_length=100, verbose_name='Pants Brand')),
                ('pants_product_name', models.CharField(blank=True, max_length=100, verbose_name='Pants Product Name')),
                ('pants_image', models.URLField(unique=True, verbose_name='Pants Image URL')),
            ],
        ),
    ]
