# Generated by Django 3.1.1 on 2020-10-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypick', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypick',
            name='top_image',
        ),
    ]
