# Generated by Django 3.1.1 on 2020-10-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brand')),
                ('classification', models.CharField(blank=True, max_length=100, verbose_name='classification')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='Product Name')),
                ('product_image', models.URLField(unique=True, verbose_name='Image URL')),
            ],
        ),
    ]
